- config.json
- hello-world/example.lua
- hello-world/hello-world_test.lua
Completes Lua for the hello world list: https://github.com/exercism/rossconf/issues/2
> Add hello-world exercise

- hamming/example.lua
- hamming/hamming_test.lua
I added a few tests to match the ones that exist in xruby:
* long identical strands return 0
* non unique character in first strand
* non unique character in second strand
* empty strings return 0
I removed the tests that pass strands of different lengths, per issue #20
> Updates hamming test and example to match hamming definition

- word-count/example.lua
- word-count/word-count_test.lua
> changes word count expectations from strings to integers

- binary/binary_test.lua
- circular-buffer/circular-buffer_test.lua
- clock/clock_test.lua
- food-chain/food-chain_test.lua
- gigasecond/gigasecond_test.lua
- grade-school/grade-school_test.lua
- grains/grains_test.lua
- hamming/hamming_test.lua
- leap/leap_test.lua
- prime-factors/prime-factors_test.lua
- rna-transcription/rna-transcription_test.lua
- robot-name/robot-name_test.lua
- roman-numerals/roman-numerals_test.lua
- scrabble-score/scrabble-score_test.lua
- space-age/space-age_test.lua
- triangle/triangle_test.lua
The current directory is already on Lua's module path by default.
> Remove unnecessary relative imports.

- prime-factors/example.lua
- prime-factors/prime-factors_test.lua
I noticed that formatting was both internally and externally inconsistent here. This should be an improvement.
> PrimeFactors -- Harmonized formatting with other exercises

- triangle/triangle_test.lua
Assertions are backwards here as well
> Fixed assertion order for Triangle

- acronym/acronym_test.lua
- acronym/example.lua
- config.json
> Added acronym exercise for Lua

- accumulate/accumulate_spec.lua
- accumulate/example.lua
- config.json
Pretty simple, feedback welcome
> Added accumulate exercise

- binary-search-tree/binary-search-tree_spec.lua
- binary-search-tree/example.lua
- config.json
I'm pretty happy with this since it explicitly requires using Lua generators/coroutines.
> Added Binary Search Tree exercise

- alphametics/alphametics_spec.lua
- alphametics/example.lua
- config.json
This problem was very interesting because:
1. It's tougher than most problems on Exercism
1. it shows how powerful `dostring` (ie: eval) is
1. It has legitimate uses for co-routines
1. It is computationally intense enough that optimizations and profiling are important
1. My solution works, but I'm sure someone else will have something better :)
I hope to see this problem on more tracks soon
> Added alphametics problem

- bowling/bowling_spec.lua
- bowling/example.lua
- config.json
For this one, I opted to require closures to be used to create the scorer object instead of using `object:method()`.
> Added bowling exercise

- config.json
Move the Hello World problem to the first problem in the track in accordance with https://github.com/exercism/todo/issues/12.
> Make the Hello World problem the first in the track

- accumulate/accumulate_spec.lua
> Verify that the input array is not mutated for accumulate

- config.json
- house/example.lua
- house/house_spec.lua
See: https://github.com/exercism/x-common/blob/master/house.md
> Added House exercise

- config.json
- etl/etl_spec.lua
- etl/example.lua
See: https://github.com/exercism/x-common/blob/master/etl.md
> Added ETL exercise

- config.json
- largest-series-product/example.lua
- largest-series-product/largest-series-product_spec.lua
See: https://github.com/exercism/x-common/blob/master/largest-series-product.md
> Added Largest Series Product

- config.json
- kindergarten-garden/example.lua
- kindergarten-garden/kindergarten-garden_spec.lua
See: https://github.com/exercism/x-common/blob/master/kindergarten-garden.md
> Added Kindergarten Garden

- config.json
- luhn/example.lua
- luhn/luhn_spec.lua
See: https://github.com/exercism/x-common/blob/master/luhn.md
> Added Luhn exercise

- config.json
- matrix/example.lua
- matrix/matrix_spec.lua
See: https://github.com/exercism/x-common/blob/master/matrix.md
> Added Matrix exercise

- config.json
- list-ops/example.lua
- list-ops/list-ops_spec.lua
See: https://github.com/exercism/x-common/blob/master/list-ops.md
Because implementing length in Lua is fairly nonsensical I opted to add `filter` in its place.
> Added List Ops exercise

- config.json
- exercises/nth-prime/example.lua
- exercises/nth-prime/nth-prime_spec.lua
See: https://github.com/exercism/x-common/blob/master/nth-prime.md
> Added nth Prime exercise

- config.json
- exercises/minesweeper/example.lua
- exercises/minesweeper/minesweeper_spec.lua
See: https://github.com/exercism/x-common/blob/master/minesweeper.md
> Added Minesweeper exercise

- config.json
- exercises/pascals-triangle/example.lua
- exercises/pascals-triangle/pascals-triangle_spec.lua
See: https://github.com/exercism/x-common/blob/master/pascals-triangle.md
> Added Pascal's Triangle exercise

- .travis.yml
- README.md
- bin/test-all
- exercises/alphametics/example.lua
- exercises/space-age/example.lua
This assumes:
- all examples are contained in a single file
- all source files are loaded from the tests with <exercise name>.lua
- all examples are valid in Lua 5.3
> Use Travis to ensure that provided examples pass all tests

- config.json
- exercises/octal/example.lua
- exercises/octal/octal_spec.lua
See: https://github.com/exercism/x-common/blob/master/octal.md
> Added Octal exercise

- config.json
- exercises/pangram/example.lua
- exercises/pangram/pangram_spec.lua
See: https://github.com/exercism/x-common/blob/master/pangram.md
See also: https://github.com/exercism/x-common/blob/master/pangram.json
> Added Pangram exercise

- config.json
- exercises/perfect-numbers/example.lua
- exercises/perfect-numbers/perfect-numbers_spec.lua
See: https://github.com/exercism/x-common/blob/master/perfect-numbers.md
> Added Perfect Numbers exercise

- config.json
- exercises/pig-latin/example.lua
- exercises/pig-latin/pig-latin_spec.lua
See: https://github.com/exercism/x-common/blob/master/pig-latin.md and https://github.com/exercism/x-common/blob/master/pig-latin.json
> Added Pig Latin exercise

- config.json
The repeat operator '*' needs to know what to repeat.
> Fix broken regexp. Closes #117

- config.json
- exercises/protein-translation/example.lua
- exercises/protein-translation/protein-translation_spec.lua
See: https://github.com/exercism/x-common/blob/master/protein-translation.md
> Added Protein Translation exercise

- config.json
- exercises/pov/example.lua
- exercises/pov/pov_spec.lua
See: https://github.com/exercism/x-common/blob/master/pov.md
> Added POV exercise

- config.json
- exercises/raindrops/example.lua
- exercises/raindrops/raindrops_spec.lua
See: [description](https://github.com/exercism/x-common/blob/master/raindrops.md) and [tests](https://github.com/exercism/x-common/blob/master/raindrops.json)
> Added raindrops exercise

- config.json
- exercises/rectangles/example.lua
- exercises/rectangles/rectangles_spec.lua
See: [description](https://github.com/exercism/x-common/blob/master/rectangles.md) and [tests in python](https://github.com/exercism/xpython/blob/master/exercises/rectangles/rectangles_count_test.py)
> Added rectangles exercise

- config.json
- exercises/pythagorean-triplet/example.lua
- exercises/pythagorean-triplet/pythagorean-triplet_spec.lua
See: [description](https://github.com/exercism/x-common/blob/master/pythagorean-triplet.md) and [javascript tests](https://github.com/exercism/xjavascript/blob/master/exercises/pythagorean-triplet/pythagorean-triplet.spec.js)
> Added pythagorean triplet exercise

- config.json
- exercises/rail-fence-cipher/example.lua
- exercises/rail-fence-cipher/rail-fence-cipher_spec.lua
See: [description](https://github.com/exercism/x-common/blob/master/rail-fence-cipher.md) and [tests](https://github.com/exercism/x-common/blob/master/rail-fence-cipher.json)
> Added rail fence cipher exercise

- config.json
- exercises/robot-simulator/example.lua
- exercises/robot-simulator/robot-simulator_spec.lua
See [description](https://github.com/exercism/x-common/blob/master/robot-simulator.md)
> Added Robot Simulator exercise

- config.json
- exercises/series/example.lua
- exercises/series/series_spec.lua
See [description](https://github.com/exercism/x-common/blob/master/series.md)
> Added Series exercise

- config.json
- exercises/sublist/example.lua
- exercises/sublist/sublist_spec.lua
See the [description](https://github.com/exercism/x-common/blob/master/sublist.md)
> Added SubList exercise

- config.json
- exercises/sum-of-multiples/example.lua
- exercises/sum-of-multiples/sum-of-multiples_spec.lua
[Exercise description](https://github.com/exercism/x-common/blob/master/sum-of-multiples.md)
> Added Sum of Multiples exercise

- config.json
- exercises/word-search/example.lua
- exercises/word-search/word-search_spec.lua
[Exercise description](https://github.com/exercism/x-common/blob/master/word-search.md)
Closes #28
> Added Word Search exercise

- exercises/scrabble-score/scrabble-score_spec.lua
> Replaced 'MULTIBILLIONAIRE' with 'OXYPHENBUTAZONE'

- exercises/binary/binary_spec.lua
> Improved tests for invalid binary numbers

- exercises/pangram/pangram_spec.lua
See: https://github.com/exercism/x-common/pull/228/files
> Synced pangram tests with x-common

- exercises/grains/example.lua
> Updated grains example for Lua 5.3.3 compatibility

- config.json
- exercises/binary/example.lua
- exercises/food-chain/example.lua
- exercises/nucleotide-count/example.lua
- exercises/prime-factors/example.lua
This includes a first pass at topics.
Closes #155
> Added `exercises` to config.json

- config.json
- exercises/diamond/diamond_spec.lua
- exercises/diamond/example.lua
See https://github.com/exercism/x-common/blob/master/diamond.md
> Added diamond exercise

- config.json
- exercises/flatten-array/example.lua
- exercises/flatten-array/flatten-array_spec.lua
See https://github.com/exercism/x-common/blob/master/flatten-array.json
> Added flatten-array exercise

- config.json
- exercises/transpose/example.lua
- exercises/transpose/transpose_spec.lua
See https://github.com/exercism/x-common/blob/master/transpose.json
> Added transpose

- config.json
- exercises/all-your-base/all-your-base_spec.lua
- exercises/all-your-base/example.lua
See https://github.com/exercism/x-common/blob/master/all-your-base.json
> Added all-your-base exercise

- docs/ABOUT.md
Just added a description for Lua.
> Added ABOUT.md

- config.json
- exercises/say/example.lua
- exercises/say/say_spec.lua
See https://github.com/exercism/x-common/blob/master/exercises/say/canonical-data.json
> Added say exercise

- config.json
- exercises/secret-handshake/example.lua
- exercises/secret-handshake/secret-handshake_spec.lua
See https://github.com/exercism/x-common/blob/master/exercises/secret-handshake/description.md
> Added secret-handshake

- config.json
- exercises/variable-length-quantity/example.lua
- exercises/variable-length-quantity/variable-length-quantity_spec.lua
See https://github.com/exercism/x-common/blob/master/exercises/variable-length-quantity/description.md
> Added variable length quantity

- SETUP.md
> Added Ubuntu and Windows instructions

- config.json
- exercises/meetup/example.lua
- exercises/meetup/meetup_spec.lua
See https://github.com/exercism/x-common/tree/master/exercises/meetup
> Added Meetup

- config.json
- exercises/tournament/example.lua
- exercises/tournament/tournament_spec.lua
See https://github.com/exercism/x-common/tree/master/exercises/tournament
> Added tournament exercise

- exercises/ocr-numbers/example.lua
- exercises/ocr-numbers/ocr-numbers_spec.lua
In task it is written:
_If the input is the incorrect size, your program should return an error._
But there were no tests for that case.
> Updated OCR exercise (more tests)

- exercises/sublist/sublist_spec.lua
Noted by @fyrchik in http://exercism.io/submissions/40b3204b77bc46659388a95b866ceca6
> Add a test to ensure that subsets are not considered sublists

- exercises/luhn/example.lua
- exercises/luhn/luhn_spec.lua
> Updated luhn to match new canonical tests

- exercises/flatten-array/flatten-array_spec.lua
> Added note regarding nils in flatten-array

- docs/RESOURCES.md
This commit also improves the clarity of the list of linting options
> resources.md: add luacheck

- exercises/hamming/example.lua
- exercises/hamming/hamming_spec.lua
adds two tests for different length strands
> hamming: update tests to match x-common

- exercises/hello-world/example.lua
- exercises/hello-world/hello-world.lua
- exercises/hello-world/hello-world_spec.lua
see https://github.com/exercism/x-common/pull/544
> hello-world: update to new x-common canonical-data

- .github/stale.yml
see #196
the only change I have made is adding the `good first patch` label to
the exemptions
> add default probot/stale.yml

- README.md
Update Lua installation link:
http://exercism.io/languages/lua/installing -> http://exercism.io/languages/lua/installation
> Update Lua installation link in README.md

- config/maintainers.json
While I realise I haven't done much in the way of maintaining this track, I
have a new job, and so have to step down as an official maintainer. Thanks &
all the best @ryanplusplus
> Update robphoenix in maintainers.json file

- config.json
- exercises/react/README.md
- exercises/react/example.lua
- exercises/react/react_spec.lua
See https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json
> Add React exercise

- .gitignore
- config.json
- exercises/isbn-verifier/README.md
- exercises/isbn-verifier/example.lua
- exercises/isbn-verifier/isbn-verifier_spec.lua
https://github.com/exercism/problem-specifications/tree/master/exercises/isbn-verifier
> Added ISBN verifier

- config/maintainers.json
A line in maintainers.json is missing a closing quotation mark
> Fix broken maintainers.json

- config.json
- exercises/resistor-color-trio/.busted
- exercises/resistor-color-trio/README.md
- exercises/resistor-color-trio/example.lua
- exercises/resistor-color-trio/resistor-color-trio.lua
- exercises/resistor-color-trio/resistor-color-trio_spec.lua
See https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color-trio
> Add resistor-color-trio exercise

- config.json
- exercises/rational-numbers/.busted
- exercises/rational-numbers/README.md
- exercises/rational-numbers/example.lua
- exercises/rational-numbers/rational-numbers.lua
- exercises/rational-numbers/rational-numbers_spec.lua
See https://github.com/exercism/problem-specifications/tree/master/exercises/rational-numbers
> Add rational numbers

- docs/INSTALLATION.md
Doc links weren't working for me so I took the liberty of updating them.
Also added instructions for Windows 10 Docker instructions.
> Added Windows Docker installation instructions, updated doc navigation

- bin/test-all
- exercises/matching-brackets/matching-brackets_spec.lua
Updated the tests. A solution I wanted to submit would pass the old tests but not the new ones.
Added a comment to indicate the tests version.
> Update matching bracket tests

- config/maintainers.json
I'm happy to help out maintaining this track :)
> Added me to maintainers.json

- bin/test-all
This accounts for the changes from https://github.com/exercism/lua/pull/287
> Fix bin/test-all

- exercises/practice/hello-world/hello-world.lua
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
> 🤖 Simplify `hello-world` stub

- exercises/practice/pig-latin/.meta/example.lua
- exercises/practice/pig-latin/pig-latin_spec.lua
Fixes https://github.com/exercism/lua/issues/328
> Update pig-latin to latest spec

- docs/INSTALLATION.md
> No sudo - install in users home directory

- config.json
- exercises/practice/resistor-color/.busted
- exercises/practice/resistor-color/.docs/instructions.append.md
- exercises/practice/resistor-color/.docs/instructions.md
- exercises/practice/resistor-color/.meta/config.json
- exercises/practice/resistor-color/.meta/example.lua
- exercises/practice/resistor-color/.meta/tests.toml
- exercises/practice/resistor-color/resistor-color.lua
- exercises/practice/resistor-color/resistor-color_spec.lua
> Add resistor-color exercise

- config.json
- exercises/practice/resistor-color-duo/.busted
- exercises/practice/resistor-color-duo/.docs/instructions.md
- exercises/practice/resistor-color-duo/.meta/config.json
- exercises/practice/resistor-color-duo/.meta/example.lua
- exercises/practice/resistor-color-duo/.meta/tests.toml
- exercises/practice/resistor-color-duo/resistor-color-duo.lua
- exercises/practice/resistor-color-duo/resistor-color-duo_spec.lua
> Add resistor-color-duo exercise

- config.json
- exercises/practice/strain/.busted
- exercises/practice/strain/.docs/instructions.md
- exercises/practice/strain/.meta/config.json
- exercises/practice/strain/.meta/example.lua
- exercises/practice/strain/.meta/tests.toml
- exercises/practice/strain/strain.lua
- exercises/practice/strain/strain_spec.lua
> Add strain exercise

- config.json
- exercises/practice/dnd-character/.busted
- exercises/practice/dnd-character/.docs/instructions.md
- exercises/practice/dnd-character/.meta/config.json
- exercises/practice/dnd-character/.meta/example.lua
- exercises/practice/dnd-character/.meta/tests.toml
- exercises/practice/dnd-character/assertions.lua
- exercises/practice/dnd-character/dnd-character.lua
- exercises/practice/dnd-character/dnd-character_spec.lua
The `ability()` and `roll_dice()` functions, and their tests, are taken from the [Java implementation](https://github.com/exercism/java/tree/main/exercises/practice/dnd-character) of this exercise.
The example character names in the tests are taken from kindergarten-garden.
assertions.lua is taken from [binary-search](https://github.com/exercism/lua/tree/main/exercises/practice/binary-search).
> Add dnd-character exercise

- config.json
- exercises/practice/darts/.busted
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/darts/.meta/example.lua
- exercises/practice/darts/.meta/tests.toml
- exercises/practice/darts/darts.lua
- exercises/practice/darts/darts_spec.lua
> Add darts exercise

- config.json
- exercises/practice/two-fer/.busted
- exercises/practice/two-fer/.docs/instructions.md
- exercises/practice/two-fer/.docs/introduction.md
- exercises/practice/two-fer/.meta/config.json
- exercises/practice/two-fer/.meta/example.lua
- exercises/practice/two-fer/.meta/tests.toml
- exercises/practice/two-fer/two-fer.lua
- exercises/practice/two-fer/two-fer_spec.lua
> Add two-fer exercise

- config.json
- exercises/practice/pop-count/.busted
- exercises/practice/pop-count/.docs/instructions.md
- exercises/practice/pop-count/.docs/introduction.md
- exercises/practice/pop-count/.meta/config.json
- exercises/practice/pop-count/.meta/example.lua
- exercises/practice/pop-count/.meta/tests.toml
- exercises/practice/pop-count/pop-count.lua
- exercises/practice/pop-count/pop-count_spec.lua
> Add pop-count

- config.json
- exercises/practice/square-root/.busted
- exercises/practice/square-root/.docs/instructions.md
- exercises/practice/square-root/.meta/config.json
- exercises/practice/square-root/.meta/example.lua
- exercises/practice/square-root/.meta/tests.toml
- exercises/practice/square-root/square-root.lua
- exercises/practice/square-root/square-root_spec.lua
> Add square-root

- config.json
- exercises/practice/armstrong-numbers/.busted
- exercises/practice/armstrong-numbers/.docs/instructions.md
- exercises/practice/armstrong-numbers/.meta/config.json
- exercises/practice/armstrong-numbers/.meta/example.lua
- exercises/practice/armstrong-numbers/.meta/tests.toml
- exercises/practice/armstrong-numbers/armstrong-numbers.lua
- exercises/practice/armstrong-numbers/armstrong-numbers_spec.lua
> Add armstrong-numbers

- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
Some updates to the docs - mostly link updates and removing/adding stuff
I mark this as WIP for now, because I want to update the `Windows 10: Docker/Install Busted` Part in `INSTALLATION.md`, because the used docker image is unmaintained, not based on the maintained busted version from lunarmodules and only runs Lua 5.1. But since I don't find any up to date busted docker container I want to build one myself, publish it and add it to the docs, which I can do on the weekend.
> WIP: Docs update

- exercises/practice/high-scores/.meta/config.json
> Fix typo in author name for high-scores

- exercises/practice/two-bucket/.meta/example.lua
- exercises/practice/two-bucket/two-bucket_spec.lua
We use the name goal_bucket_number instead of
goal_bucket_volume.
https://forum.exercism.org/t/two-bucket-exercise/8455
> two-bucket: rename goal_bucket_volume

- docs/TESTS.md
As described in issue #430 I have added debugging unit test instructions to the TESTS.md page on the Lua track.
Feedback welcome :)
> Add unit test debugging instructions #430

- config.json
- exercises/practice/knapsack/.busted
- exercises/practice/knapsack/.docs/instructions.md
- exercises/practice/knapsack/.meta/config.json
- exercises/practice/knapsack/.meta/example.lua
- exercises/practice/knapsack/.meta/tests.toml
- exercises/practice/knapsack/knapsack.lua
- exercises/practice/knapsack/knapsack_spec.lua
This is an exercise featured in 48 in 24 that the Lua track doesn't have implemented yet (see the full list at https://exercism.org/challenges/48in24/implementation_status).
> Add Knapsack

- config.json
- exercises/practice/spiral-matrix/.busted
- exercises/practice/spiral-matrix/.docs/instructions.md
- exercises/practice/spiral-matrix/.meta/config.json
- exercises/practice/spiral-matrix/.meta/example.lua
- exercises/practice/spiral-matrix/.meta/tests.toml
- exercises/practice/spiral-matrix/spiral-matrix.lua
- exercises/practice/spiral-matrix/spiral-matrix_spec.lua
This is an exercise featured in 48 in 24 that the Lua track doesn't have implemented yet (see the full list at https://exercism.org/challenges/48in24/implementation_status).
> Add spiral-matrix

- exercises/practice/eliuds-eggs/eliuds-eggs.lua
I missed this in https://github.com/exercism/lua/pull/447
> Fix Eliud's Eggs skeleton

- concepts/basics/.meta/config.json
- concepts/basics/about.md
- concepts/basics/introduction.md
- concepts/basics/links.json
- config.json
- exercises/concept/lasagna/.docs/hints.md
- exercises/concept/lasagna/.docs/instructions.md
- exercises/concept/lasagna/.docs/introduction.md
- exercises/concept/lasagna/.meta/config.json
- exercises/concept/lasagna/.meta/exemplar.lua
- exercises/concept/lasagna/lasagna.lua
- exercises/concept/lasagna/lasagna_spec.lua
I had a day off and wanted to write the hole concept and concept practice stuff, but I was constantly interrupted, so I only managed to write the concept. :smiling_face_with_tear:  But I guess it is good to open this as a WIP PR so the spelling and correctness can be checked while I finish this in the next days :slightly_smiling_face:
> concepts: basic concept

- exercises/concept/lasagna/.docs/introduction.md
- exercises/concept/lasagna/.docs/introduction.md.tpl
So configlet's generate command can be used to create it. `introduction.md` was regenerated with configlet using the template.
> added introduction.md.tpl to lasagna concept exercise

- config.json
Set the concept_exercises to true and changed the ident_size to 2 to match the ident size we use everywhere
> config.json: concept_exercises true and editor ident_size 2

- exercises/concept/cars-assemble/cars-assemble.lua
I missed that one :sweat_smile:
> fixed wrong parameters in calculate_cost solution template

- config.json
- exercises/practice/rotational-cipher/.busted
- exercises/practice/rotational-cipher/.docs/instructions.md
- exercises/practice/rotational-cipher/.meta/config.json
- exercises/practice/rotational-cipher/.meta/example.lua
- exercises/practice/rotational-cipher/.meta/tests.toml
- exercises/practice/rotational-cipher/rotational-cipher.lua
- exercises/practice/rotational-cipher/rotational-cipher_spec.lua
This is scheduled for #48in24 week 35
> Add Rotational Cipher

- concepts/booleans/.meta/config.json
- concepts/booleans/about.md
- concepts/booleans/introduction.md
- concepts/booleans/links.json
- config.json
- exercises/concept/pacman-rules/.busted
- exercises/concept/pacman-rules/.docs/hints.md
- exercises/concept/pacman-rules/.docs/instructions.md
- exercises/concept/pacman-rules/.docs/introduction.md
- exercises/concept/pacman-rules/.docs/introduction.md.tpl
- exercises/concept/pacman-rules/.meta/config.json
- exercises/concept/pacman-rules/.meta/exemplar.lua
- exercises/concept/pacman-rules/pacman-rules.lua
- exercises/concept/pacman-rules/pacman-rules_spec.lua
> concepts: booleans concept

- config.json
- exercises/practice/high-scores/high-scores.lua
Fixes https://github.com/exercism/lua/issues/429
> Improve high scores experience

- exercises/practice/high-scores/.docs/instructions.append.md
- exercises/practice/high-scores/high-scores.lua
Discussed in [the forum](http://forum.exercism.org/t/high-scores-stub/12879)
> Add a hint into the high-scores stub

- config.json
> Sort practice exercises

- exercises/practice/alphametics/.docs/instructions.md
- exercises/practice/alphametics/.meta/config.json
- exercises/practice/darts/.docs/instructions.md
- exercises/practice/darts/.meta/config.json
- exercises/practice/hello-world/.meta/config.json
- exercises/practice/pascals-triangle/.docs/instructions.md
- exercises/practice/pascals-triangle/.docs/introduction.md
- exercises/practice/perfect-numbers/.docs/instructions.md
- exercises/practice/pig-latin/.docs/instructions.md
- exercises/practice/pythagorean-triplet/.meta/config.json
- exercises/practice/raindrops/.meta/config.json
- exercises/practice/strain/.meta/config.json
- exercises/practice/two-bucket/.docs/instructions.md
- exercises/practice/yacht/.meta/config.json
- alphametics
- darts
- hello-world
- pascals-triangle
- perfect-numbers
- pig-latin
- pythagorean-triplet
- raindrops
- strain
- two-bucket
- yacht
> Sync exercise instructions

- bin/verify-exercises-in-docker
From [generic-track](https://github.com/exercism/generic-track/blob/main/bin/verify-exercises-in-docker)
> Add bin/verify-exercises-in-docker

- exercises/practice/crypto-square/.meta/tests.toml
- exercises/practice/crypto-square/crypto-square_spec.lua
> Sync crypto-square

- config.json
- exercises/practice/flower-field/.busted
- exercises/practice/flower-field/.docs/instructions.md
- exercises/practice/flower-field/.docs/introduction.md
- exercises/practice/flower-field/.meta/config.json
- exercises/practice/flower-field/.meta/example.lua
- exercises/practice/flower-field/.meta/spec_generator.lua
- exercises/practice/flower-field/.meta/tests.toml
- exercises/practice/flower-field/flower-field.lua
- exercises/practice/flower-field/flower-field_spec.lua
> Add flower-field exercise, deprecate minesweeper

- config.json
Fixes issue noted by @keiravillekode in https://github.com/exercism/lua/pull/556#discussion_r2162685507.
> Fix flower-field's name in config.json

- exercises/practice/space-age/.docs/instructions.md
- exercises/practice/space-age/.docs/introduction.md
- exercises/practice/space-age/.meta/tests.toml
We exclude the new test case
- invalid planet causes error (57b96e2a-1178-40b7-b34d-f3c9c34e4bf4)
[no important files changed]
> sync space-age

- exercises/practice/sublist/.meta/example.lua
- exercises/practice/sublist/.meta/spec_generator.lua
- exercises/practice/sublist/.meta/tests.toml
- exercises/practice/sublist/sublist.lua
- exercises/practice/sublist/sublist_spec.lua
Related to https://github.com/exercism/lua/issues/577
> Update sublist tests

- exercises/practice/list-ops/.meta/tests.toml
- exercises/practice/list-ops/list-ops_spec.lua
Closes https://github.com/exercism/lua/issues/577
> Sync list-ops tests
