- binary/binary_test.lua
- binary/example.lua
- word-count/example.lua
- word-count/word-count_test.lua
I believe such simple exercises do not need the unnecessary coding overhead of creating classes, so I changed them into single  functions.
> Remove unnecessary classes on word-count and binary

- roman-numerals/example.lua
- roman-numerals/roman-numerals_test.lua
- scrabble-score/example.lua
- scrabble-score/scrabble-score_test.lua
Ever since the extinguishing of `module()` the "lunatic" way of making modules is to return a table with the module's content.
> Modules as tables on scrabble-score and roman-numerals

- grains/example.lua
- grains/grains_test.lua
- The sample solution did not work; fixed by using bitwise operator to ensure that 64-bit integers are used
- Assertion argument order was messed up so that the expected value was given as the actual value and vice-versa; reordered
> Fix grains (sample solution and assertion order)

- prime-factors/example.lua
- prime-factors/prime-factors_test.lua
The prime factors tests depend upon a global variable being defined in `prime-factors.lua`. This change removes the global from the sample solution and updates the tests to use the function exported from the source file.
I'm honestly surprised that this worked and I think it might be due to a pecularity in busted. I'm fairly certain that global variables can't escape modules in vanilla Lua.
> Updated prime factors tests to not depend upon global variables

- clock/clock_test.lua
For whatever reason the clock tests use both `tostring(clock)` and `clock:tostring()`. This seems needlessly confusing and non-idiomatic so I modified the tests to only  use the built-in `tostring`.
> Use Lua's built-in tostring instead of tostring method defined on Clock

- README.md
- SETUP.md
Homebrew no longer has a standalone luarocks package, it is packaged along with Lua. This updates the documentation to reflect this.
> Updated documentation to indicate that Luarocks comes with Lua from Homebrew

- circular-buffer/circular-buffer_test.lua
Following suit with other language tracks:
Ruby:
https://github.com/exercism/xruby/commit/5560b7a0e032bdf4bca753d4aba4625340853d1c
Go:
https://github.com/exercism/xgo/commit/6b41d2f925a7b35140701a8290e7d9a6155ac315
Rust:
https://github.com/exercism/xrust/commit/e4990f1b0e8c9d16053012b13aaaeb03ac141383
Javscript:
https://github.com/exercism/xjavascript/commit/301dd0069e5cd60f336c6a622fac1ea9f3fd1357
> circular-buffer: Test overwrite on non-full buffer

- binary-search/TracedArray.lua
> Track unique accesses to traced arrays for binary search, not total accesses

- exercises/largest-series-product/largest-series-product_spec.lua
At first glance, you might say that this is already being handled by the
case that ensures that the span is less than the number of digits in the
string.
But actually I argue it is important to have this case, to ensure that a
solution of the form "return 1 if the string is empty" does not pass the
tests. Such a solution would be wrong and it would have to be caught by
this particular test.
> largest-series-product: Test for empty digits nonzero span

- exercises/triangle/triangle_spec.lua
> Removed gray area test in Triangle exercise

- exercises/custom-set/custom-set_spec.lua
I saw in a solution that `#` was being used to calculate the size of a set and no tests were passing. This change ensures that this failure will be caught.
> Improve custom set tests so that # cannot be used to incorrectly calculate size

- exercises/sum-of-multiples/example.lua
- exercises/sum-of-multiples/sum-of-multiples_spec.lua
Closes #134 
I think in this case that the test name made it extremely clear what the expected behavior was, but it's better to match everything else.
> Removed defaults for sum-of-multiples

- exercises/pig-latin/example.lua
- exercises/pig-latin/pig-latin_spec.lua
@wlspaldi noticed that the behavior wasn't correct when words were capitalized. This corrects the test and implementation.
> Pig Latin: Always identify prefixes by using lowercased word

- exercises/run-length-encoding/example.lua
- exercises/run-length-encoding/run-length-encoding_spec.lua
Noted by @fyrchik in http://exercism.io/submissions/b6111df3545d4af1b2ca3e8219bb8bdd
> Add tests to ensure that multi-digit run lengths are supported for en/decode

- exercises/transpose/example.lua
- exercises/transpose/transpose_spec.lua
I think this is the correct behaviour for string with empty lines, because it is reasonable to expect that `transpose(transpose(input)) == input`. If we just throw empty lines, we lose some information.
Interesting thing i noticed: if you change anything in pattern it will stop work.
Yes, `([^\n]*)` or `[^\n]*\n?` will NOT work. It is counterintuitive (especially in second case, where i just throw brackets). I don't know if this is intended behaviour in Lua.
> Updated Transpose exercise (test with empty lines)

- exercises/TRACK_HINTS.md
as @petertseng commented in https://github.com/exercism/xlua/issues/188#issuecomment-280956956
it may be worth including a reminder for how to run the tests (for some
there can be long gaps between exercises in languages not often used) as
well as a link to the more detailed language page on the exercism.io
site.
> add TRACK_HINTS.md

- config.json
- exercises/accumulate/accumulate_spec.lua
- exercises/accumulate/example.lua
When migrating the data from v1 to v2, we will lose all the solutions submitted to
deprecated exercises, unless they exist in the track configuration.
This adds the deprecated accumulate exercise back, leaving it deprecated so that it
doesn't actively show up as part of the track.
We can delete it from the track again after we launch v2, if we want to.
> Add back deleted, deprecated accumulate exercise

- config/exercise_readme.go.tmpl
- docs/EXERCISE_README_INSERT.md
- exercises/all-your-base/README.md
- exercises/alphametics/README.md
- exercises/bank-account/README.md
- exercises/custom-set/README.md
- exercises/isbn-verifier/README.md
- exercises/list-ops/README.md
- exercises/minesweeper/README.md
- exercises/protein-translation/README.md
- exercises/react/README.md
- exercises/rectangles/README.md
- exercises/reverse-string/README.md
- exercises/rna-transcription/README.md
- exercises/sublist/README.md
- exercises/tournament/README.md
- exercises/word-search/README.md
Now that we're operating with a track-wide template for generating exercise
READMEs we no longer need a separate markdown document to use for hints
and instructions that apply to all the exercises in a track. These instructions
can be defined directly in the template.
The first commit regenerates the exercise READMEs to pick up tweaks to problem descriptions, which have been updated with various formatting changes, whitespace changes, and clarifications to the description.
That gives us a clean diff when inlining the template and regenerating.
Ref: https://github.com/exercism/meta/issues/94
> Inline the exercise README insert

- docs/INSTALLATION.md
Luarocks needs lua include files it to compile some dependencies.
In my system busted's installation failed because lua include files were missing.
> install: add liblua5.3-dev as dependency

- exercises/binary-search/assertions.lua
- exercises/binary-search/binary-search_spec.lua
When working through the binary-search exercise, my naive solution was not efficient enough and the failure messages displayed to me looked like:
```
binary-search busted --filter 'longer array'
◼
0 successes / 1 failure / 0 errors / 0 pending : 0.009913 seconds
Failure → ./binary-search_spec.lua @ 33
binary-search should find an element in a longer array in less than log(n) accesses
./binary-search_spec.lua:37: assertion failed!
```
This PR attempts to make the failure message clearer, so that it looks like:
```
binary-search busted --filter 'longer array'
◼
0 successes / 1 failure / 0 errors / 0 pending : 0.012731 seconds
Failure → ./binary-search_spec.lua @ 33
binary-search should find an element in a longer array in less than log(n) accesses
./binary-search_spec.lua:37: Expected …
```
> binary-search: clearer failure messages for <= comparisons

- docs/INSTALLATION.md
Luarocks is distributed seperately to lua with homebrew.
> This was missing in the documentation.

- exercises/bank-account/bank-account_spec.lua
This typo makes busted show somewhat wrong output.
> bank-account: fix typo in bank-account_spec.lua

- docs/INSTALLATION.md
Previous instructions no longer work for a multitude of reasons outlined in exercism/support#80
LuaRocks is notoriously difficult to set up on Windows, and many Rocks are not compatible regardless.
Chocolatey as used in previous instructions only installed LuaRocks, but no C compiler, and doesn't know how to configure such a compiler to work with LuaRocks even if it did install one, et cetera.
These new instructions, unfortunately, *require* Windows 10, since they rely on Windows Subsystem for Linux, but I believe it's by far the easiest way to get Busted running on a Windows 10 machine.
I don't have any good answers for what to tell Windows 7 users.
> Revise Windows install instructions to use WSL

- exercises/practice/bank-account/bank-account_spec.lua
Small typo in the tests, which unfortunately suggests the opposite meaning.
> Fix typo in bank-account tests

- exercises/practice/nucleotide-count/nucleotide-count_spec.lua
Function [`parse_test_file`](https://github.com/exercism/lua-test-runner/blob/66c56800e16e3123d4c7eb1dc81788f22d87d508/handler/exercism.lua#L12) in test runner could not parse the spec file due to the typo in indentation.
This leads to correct solutions being reported as "Failed" on https://exercism.org/tracks/lua/exercises/nucleotide-count.
> Fix unparsable indentation in spec for test runner

- docs/INSTALLATION.md
Don't need an alias to create a function, just use a function
> Simplify the Windows 10 Docker instructions.

- exercises/shared/.docs/tests.md
My previous PR #350 will affect the website's Lua track docs.
This change manifests in the downloaded HELP.md file (https://exercism.org/docs/building/tracks/presentation#h-help-md)
> Update the testing doc that's included in the downloaded HELP.md

- exercises/practice/largest-series-product/.docs/instructions.md
- exercises/practice/largest-series-product/.docs/introduction.md
- exercises/practice/largest-series-product/.meta/tests.toml
- exercises/practice/largest-series-product/largest-series-product_spec.lua
The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …
> Sync largest-series-product docs with problem-specifications

- exercises/practice/nth-prime/nth-prime_spec.lua
To avoid accidentally passing the performance test with a caching technique like in iteration 1 here: https://exercism.org/tracks/lua/exercises/nth-prime/solutions/bkhl
> Reorder tests in nth-prime_spec.lua

- config.json
This slug was deprecated last year in favor of bottle-song, which has now been implemented.
See https://github.com/exercism/problem-specifications/blob/main/exercises/beer-song/.deprecated
> Deprecate beer-song

- exercises/practice/armstrong-numbers/.meta/example.lua
- exercises/practice/armstrong-numbers/armstrong-numbers.lua
- exercises/practice/armstrong-numbers/armstrong-numbers_spec.lua
- exercises/practice/pop-count/.meta/example.lua
- exercises/practice/pop-count/pop-count.lua
- exercises/practice/pop-count/pop-count_spec.lua
- exercises/practice/square-root/.meta/example.lua
- exercises/practice/square-root/square-root.lua
- exercises/practice/square-root/square-root_spec.lua
- exercises/practice/two-fer/.meta/example.lua
- exercises/practice/two-fer/two-fer.lua
- exercises/practice/two-fer/two-fer_spec.lua
This fixes formatting inconsistencies with the other exercises in the track
> Use snake case instead of camel case for function names

- exercises/practice/custom-set/custom-set_spec.lua
The LuaFormatter moved the function expression on a new line, which confuses the lua-test-runner. Fixed it and deactivated the LuaFormater for the test.
Closes #434
> fixed lua-test-runner error with custom-set_spec.lua

- exercises/practice/custom-set/custom-set_spec.lua
Was a typo declaring non empty set as not disjoint with empty set.  Now correctly states that it should be disjoint.
Closes #433
> Corrected test description for disjoint sets.

- exercises/concept/lasagna/.busted
- exercises/concept/lasagna/lasagna_spec.lua
Without this, `busted` expects the tests to be in `spec/`:
> Add .busted to fix lasagna tests

- exercises/practice/crypto-square/.meta/example.lua
- exercises/practice/crypto-square/crypto-square_spec.lua
The current tests do not actually test anything. Problem exposed during a mentoring session.
The example needed updating to pass the tests.
> crypto-square: fix tests not comparing actual to expected

- exercises/practice/triangle/.docs/instructions.md
The instructions did not mention that the use of the error keyword is required. In addition, following the Concepts up to this exercise did not mention the error keyword, as such additional instructions have been added.
#496 
Edit: https://forum.exercism.org/t/mentioning-of-the-error-keyword/12686
> Update instructions.md for Lua error handling

- README.md
- bin/generate-spec
- config.json
- exercises/practice/rotational-cipher/.meta/config.json
- exercises/practice/saddle-points/.busted
- exercises/practice/saddle-points/.docs/instructions.md
- exercises/practice/saddle-points/.docs/introduction.md
- exercises/practice/saddle-points/.meta/config.json
- exercises/practice/saddle-points/.meta/example.lua
- exercises/practice/saddle-points/.meta/spec_generator.lua
- exercises/practice/saddle-points/.meta/tests.toml
- exercises/practice/saddle-points/saddle-points.lua
- exercises/practice/saddle-points/saddle-points_spec.lua
- exercises/practice/two-bucket/.meta/config.json
- exercises/practice/wordy/.meta/config.json
- exercises/practice/yacht/.meta/config.json
I also extended the test generator to allow test helpers to be included so that I could implement an order-independent comparison for the result set.
> Add saddle points practice exercise

- exercises/practice/high-scores/.docs/instructions.append.md
I copied the article to my GitHub.io -- https://glennj.github.io/exercism/lua/oop
> move OOP article link off-site

- exercises/practice/book-store/book-store_spec.lua
fixes exercism/lua-test-runner#76
> fixed lua-test-runner error with book-store_spec.lua

- exercises/practice/saddle-points/.meta/spec_generator.lua
- exercises/practice/saddle-points/saddle-points_spec.lua
Noted by @glennj: https://forum.exercism.org/t/saddle-points-exercise-tests/13035/1
This was my mistake, I didn't need the order-independent comparison at first because only one test fails without it and I obviously didn't make sure that the helper function actually worked.
> Fix saddle-points spec

- bin/generate-spec
- exercises/practice/book-store/book-store_spec.lua
- exercises/practice/state-of-tic-tac-toe/state-of-tic-tac-toe_spec.lua
In https://github.com/exercism/lua/pull/523, @keiravillekode mentioned that the `reimplements` was handled by manually updating the generated spec. This updates the spec generator so that only tests included via `tests.toml` are included in the generated spec.
> Spec generator - Respect tests.toml

- config.json
These exercises have been replaced by all-your-base https://github.com/exercism/problem-specifications/issues/279
resolves #532
> Deprecate binary and octal exercises

- exercises/practice/list-ops/.meta/example.lua
- exercises/practice/list-ops/.meta/spec_generator.lua
- exercises/practice/list-ops/.meta/tests.toml
- exercises/practice/list-ops/list-ops.lua
- exercises/practice/list-ops/list-ops_spec.lua
> Update list-ops tests

- exercises/practice/word-count/.meta/example.lua
- exercises/practice/word-count/.meta/spec_generator.lua
- exercises/practice/word-count/.meta/tests.toml
- exercises/practice/word-count/word-count.lua
- exercises/practice/word-count/word-count_spec.lua
> Update word-count tests

- exercises/practice/gigasecond/gigasecond_spec.lua
This pull request updates the gigasecond exercise tests to use dates that are supported by Lua’s ``os.time``. Previously, test 3 used the date 1959-07-19, which caused ``os.time`` to return nil and made the ``any_date`` parameter in ``gigasecond.anniversary`` nil. The test has now been updated to use 2009-01-19, which allows the function to correctly calculate the gigasecond anniversary and ensures the test passes as intended.
> Fix test dates for gigasecond
